export const CONTRACT_ID =
  process.env.NEXT_PUBLIC_CONTRACT_ID ??
  "CDRIREBGHCOS3YU6KMFGXLLBOXCWMYXX2VQ7AYX2G5YBWVPNJ7SHHFHJ";

export const RPC_URL =
  process.env.NEXT_PUBLIC_RPC_URL ?? "https://soroban-testnet.stellar.org";

export const NETWORK_PASSPHRASE =
  process.env.NEXT_PUBLIC_NETWORK_PASSPHRASE ??
  "Test SDF Network ; September 2015";

export const BID_TOKEN =
  process.env.NEXT_PUBLIC_BID_TOKEN ??
  "CBIELTK6YBZJU5UPH73ZZ7RMHWAVP5FM646FGAWL25LETVSEUYEKNMYF";

export const PRIZE_TOKEN =
  process.env.NEXT_PUBLIC_PRIZE_TOKEN ??
  "CBIELTK6YBZJU5UPH73ZZ7RMHWAVP5FM646FGAWL25LETVSEUYEKNMYF";

export const TOKEN_DECIMALS = 7;
